import { ENGINE_MANAGE } from '../scripts/page-name'

/**
 * 命名规则:模块名_页面名_功能名
 * */

//PAGINATION
export const PAGE_INDEX = 'DATA_PROCESS_TASK_LIST_PAGE_INDEX'
export const PAGE_TOTAL = 'DATA_PROCESS_TASK_LIST_PAGE_TOTAL'
export const PAGE_SIZE = 'DATA_PROCESS_TASK_LIST_PAGE_SIZE'
//SORT
export const DATA_PROCESS_TASK_DETAIL_SORT = 'DATA_PROCESS_TASK_DETAIL_SORT'
export const DATA_PROCESS_TASK_LIST_SORT = 'DATA_PROCESS_TASK_LIST_SORT'
export const DATA_ACCESS_LIST_SORT = 'DATA_ACCESS_LIST_SORT'
export const DATA_ACCESS_CHARGING_SORT = 'DATA_ACCESS_CHARGING_SORT'
export const DATA_ACCESS_API_DETAIL_SORT = 'DATA_ACCESS_API_DETAIL_SORT'
export const FLOW_MANAGE_LIST_SORT = 'FLOW_MANAGE_LIST_SORT'
export const FLOW_VERSION_LIST_SORT = 'FLOW_VERSION_LIST_SORT'
export const FLOW_VERSION_RESULT_SORT = 'FLOW_VERSION_RESULT_SORT'
export const SNAPSHOT_LIST_SORT = 'SNAPSHOT_LIST_SORT'

//SEARCH
export const DATA_PROCESS_TASK_DETAIL_SEARCH_KEY = 'DATA_PROCESS_TASK_DETAIL_SEARCH_KEY'
export const DATA_PROCESS_TASK_LIST_SEARCH_KEY = 'DATA_PROCESS_TASK_LIST_SEARCH_KEY'
export const DATA_ACCESS_LIST_SEARCH_KEY = 'DATA_ACCESS_LIST_SEARCH_KEY'
export const DATA_ACCESS_CHARGING_API_NO = 'DATA_ACCESS_CHARGING_API_NO'
export const DATA_ACCESS_CHARGING_COMPANY_NO = 'DATA_ACCESS_CHARGING_COMPANY_NO'
export const DATA_ACCESS_API_DETAIL_SEARCH_KEY = 'DATA_ACCESS_API_DETAIL_SEARCH_KEY'
export const DATA_ACCESS_API_DETAIL_STATUS_TYPE = 'DATA_ACCESS_API_DETAIL_STATUS_TYPE'
export const DATA_ACCESS_API_DETAIL_DATE_RANGE = 'DATA_ACCESS_API_DETAIL_DATE_RANGE'
export const DATA_ACCESS_API_DETAIL_API_NO = 'DATA_ACCESS_API_DETAIL_API_NO'
export const DATA_ACCESS_API_DETAIL_COMPANY_NO = 'DATA_ACCESS_API_DETAIL_COMPANY_NO'
export const DATA_ACCESS_CHARGING_DATE_RANGE = 'DATA_ACCESS_CHARGING_DATE_RANGE'
export const ENGINE_MANAGE_DECISION_RESULT_LIST_SEARCH_KEY = 'ENGINE_MANAGE_DECISION_RESULT_LIST_SEARCH_KEY'
export const ENGINE_MANAGE_DECISION_RESULT_LIST_REQUEST_TYPE = 'ENGINE_MANAGE_DECISION_RESULT_LIST_REQUEST_TYPE'
export const ENGINE_MANAGE_DECISION_RESULT_LIST_STATUS = 'ENGINE_MANAGE_DECISION_RESULT_LIST_STATUS'
	
export const MONITOR_REPORT_ENGINE_ENGINE_ID = 'MONITOR_REPORT_ENGINE_ENGINE_ID'
export const MONITOR_REPORT_ENGINE_SNAPSHOT_ID = 'MONITOR_REPORT_ENGINE_SNAPSHOT_ID'
export const MONITOR_REPORT_ENGINE_DATE_RANGE = 'MONITOR_REPORT_ENGINE_DATE_RANGE'
export const MONITOR_REPORT_ENGINE_CLASSIFY = 'MONITOR_REPORT_ENGINE_CLASSIFY'
export const MONITOR_REPORT_ENGINE_TYPE = 'MONITOR_REPORT_ENGINE_TYPE'
export const MONITOR_REPORT_BUSINESS_CLASSIFY = 'MONITOR_REPORT_BUSINESS_CLASSIFY'
export const MONITOR_REPORT_BUSINESS_TYPE = 'MONITOR_REPORT_BUSINESS_TYPE'
export const MONITOR_REPORT_BUSINESS_DATE_RANGE = 'MONITOR_REPORT_BUSINESS_DATE_RANGE'
export const MONTIOR_REPORT_BUSINESS_DIMENSION = 'MONTIOR_REPORT_BUSINESS_DIMENSION'
export const ALARM_MANAGE_LIST_SEARCH_KEY = 'ALARM_MANAGE_LIST_SEARCH_KEY'
export const ALARM_MANAGE_LIST_ALARM_TYPE = 'ALARM_MANAGE_LIST_ALARM_TYPE'
export const ALARM_MANAGE_LIST_ALARM_STATE = 'ALARM_MANAGE_LIST_ALARM_STATE' 
export const ALARM_MANAGE_LIST_USER_ID = 'ALARM_MANAGE_LIST_USER_ID'
export const ALARM_MANAGE_LIST_SELECTED_ROW = 'ALARM_MANAGE_LIST_SELECTED_ROW'
export const FLOW_MANAGE_LIST_SEARCH_KEY = 'FLOW_MANAGE_LIST_SEARCH_KEY'
export const FLOW_VERSION_LIST_STATUS = 'FLOW_VERSION_LIST_STATUS'
export const FLOW_VERSION_LIST_SEARCH_KEY = 'FLOW_VERSION_LIST_SEARCH_KEY'
export const FLOW_VERSION_RESULT_SEARCH_KEY = 'FLOW_VERSION_RESULT_SEARCH_KEY'
export const FLOW_VERSION_RESULT_STATUS = 'FLOW_VERSION_RESULT_STATUS'
export const FLOW_VERSION_RESULT_DATE_RANGE = 'FLOW_VERSION_RESULT_DATE_RANGE'
export const FLOW_VERSION_RESULT_FLOW_VERSION_NAME = 'FLOW_VERSION_RESULT_FLOW_VERSION_NAME'
//FILTER
export const DATA_PROCESS_TASK_DETAIL_STATUS_TYPE = 'DATA_PROCESS_TASK_DETAIL_STATUS_TYPE'
export const DATA_PROCESS_TASK_DETAIL_BEFORE_TIME = 'DATA_PROCESS_TASK_DETAIL_BEFORE_TIME'
export const DATA_PROCESS_TASK_LIST_FILTER = 'DATA_PROCESS_TASK_LIST_FILTER'
export const DATA_ACCESS_LIST_FILTER = 'DATA_ACCESS_LIST_FILTER'
export const SNAPSHOT_MANAGE_DECISION_RESULT_OVERVIEW_DATE_RANGE = 'SNAPSHOT_MANAGE_DECISION_RESULT_OVERVIEW_DATE_RANGE'
export const ENGINE_MANAGE_DECISION_RESULT_LIST_DATE_RANGE = 'ENGINE_MANAGE_DECISION_RESULT_LIST_DATE_RANGE'
//CONST
export const CURRENT_PAGE_NAME = 'CURRENT_PAGE_NAME'

//FIELD
export const LOAD_FIELD = 'LOAD_FIELD'

//FLOW_TAB
export const FLOW_TAB_STORE_KEY = 'FLOW_TAB_STORE_KEY'
export const FLOW_TAB_BACK_ROUTE_NAME = 'FLOW_TAB_BACK_ROUTE_NAME'
